source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'html5-boilerplate'
gem 'jquery-rails'
gem 'devise'
gem 'will_paginate'
gem 'state_machine'
gem 'formtastic'
gem 'carmen'
gem 'meta_where'
gem 'high_voltage'
gem 'cancan'
gem "tabs_on_rails"

group :development, :test do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'shoulda'
  gem 'capybara'
  gem 'launchy'
  gem 'factory_girl_rails'
  gem 'annotate-models'
  gem 'haml-rails'
  gem 'database_cleaner'
  gem 'ruby-debug19'
end
