require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceRemindersController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceReminder. As you add validations to ServiceReminder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all service_reminders as @service_reminders" do
      service_reminder = ServiceReminder.create! valid_attributes
      get :index
      assigns(:service_reminders).should eq([service_reminder])
    end
  end

  describe "GET show" do
    it "assigns the requested service_reminder as @service_reminder" do
      service_reminder = ServiceReminder.create! valid_attributes
      get :show, :id => service_reminder.id.to_s
      assigns(:service_reminder).should eq(service_reminder)
    end
  end

  describe "GET new" do
    it "assigns a new service_reminder as @service_reminder" do
      get :new
      assigns(:service_reminder).should be_a_new(ServiceReminder)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_reminder as @service_reminder" do
      service_reminder = ServiceReminder.create! valid_attributes
      get :edit, :id => service_reminder.id.to_s
      assigns(:service_reminder).should eq(service_reminder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceReminder" do
        expect {
          post :create, :service_reminder => valid_attributes
        }.to change(ServiceReminder, :count).by(1)
      end

      it "assigns a newly created service_reminder as @service_reminder" do
        post :create, :service_reminder => valid_attributes
        assigns(:service_reminder).should be_a(ServiceReminder)
        assigns(:service_reminder).should be_persisted
      end

      it "redirects to the created service_reminder" do
        post :create, :service_reminder => valid_attributes
        response.should redirect_to(ServiceReminder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_reminder as @service_reminder" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceReminder.any_instance.stub(:save).and_return(false)
        post :create, :service_reminder => {}
        assigns(:service_reminder).should be_a_new(ServiceReminder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceReminder.any_instance.stub(:save).and_return(false)
        post :create, :service_reminder => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_reminder" do
        service_reminder = ServiceReminder.create! valid_attributes
        # Assuming there are no other service_reminders in the database, this
        # specifies that the ServiceReminder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceReminder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => service_reminder.id, :service_reminder => {'these' => 'params'}
      end

      it "assigns the requested service_reminder as @service_reminder" do
        service_reminder = ServiceReminder.create! valid_attributes
        put :update, :id => service_reminder.id, :service_reminder => valid_attributes
        assigns(:service_reminder).should eq(service_reminder)
      end

      it "redirects to the service_reminder" do
        service_reminder = ServiceReminder.create! valid_attributes
        put :update, :id => service_reminder.id, :service_reminder => valid_attributes
        response.should redirect_to(service_reminder)
      end
    end

    describe "with invalid params" do
      it "assigns the service_reminder as @service_reminder" do
        service_reminder = ServiceReminder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceReminder.any_instance.stub(:save).and_return(false)
        put :update, :id => service_reminder.id.to_s, :service_reminder => {}
        assigns(:service_reminder).should eq(service_reminder)
      end

      it "re-renders the 'edit' template" do
        service_reminder = ServiceReminder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceReminder.any_instance.stub(:save).and_return(false)
        put :update, :id => service_reminder.id.to_s, :service_reminder => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_reminder" do
      service_reminder = ServiceReminder.create! valid_attributes
      expect {
        delete :destroy, :id => service_reminder.id.to_s
      }.to change(ServiceReminder, :count).by(-1)
    end

    it "redirects to the service_reminders list" do
      service_reminder = ServiceReminder.create! valid_attributes
      delete :destroy, :id => service_reminder.id.to_s
      response.should redirect_to(service_reminders_url)
    end
  end

end
